package evoter.server.http.request.interfaces;

import java.util.Map;
import com.sun.net.httpserver.HttpExchange;

import evoter.share.dao.UserDAO;
import evoter.share.utils.URIRequest;

/**
 * 
 * @author btdiem
 *
 */
public interface IAccountService {

	public static final String BEAN_NAME = "accountService";
	/**
	 * Response clients a userkey generated from {@link UserDAO#USER_NAME} </br>
	 * and {@link UserDAO#PASSWORD} if username and password exist in database </br> 
	 * or response a null value if username and password do not exist in database </br>
	 * or response a @ {@link URIRequest#FAILURE_MESSAGE } if there is an{@link Exception} </br>    
	 * 
	 * @param exchange {@link HttpExchange} communicates between server and clients </br>
	 * @param parameters contains : </br>
	 * {@link UserDAO.USER_NAME} </br>
	 * {@link UserDAO.PASSWORD} </br>
	 */
	public Object doLogin(Map<String,Object> parameters);	

	/**
	 * Response clients a {@link URIRequest#SUCCESS_MESSAGE} if userkey value exists </br>
	 * or response clients a {@link URIRequest#FAILURE_MESSAGE} if userkey does not exist </br>
	 * 
	 * @param exchange {@link HttpExchange} communicate between clients and server </br>
	 * @param parameters contains {@link UserDAO#USER_KEY} </br>
	 */
	public Object doLogout(Map<String,Object> parameters);

	/**
	 * Check if email exists in the database and return a success or failure response </br> 
	 * @param httpExchange {@link HttpExchange} communicates between client and server </br>
	 * @param parameters contains email address </br>
	 */
	public Object doResetPassword(Map<String, Object> parameters) ;
	/**
	 * Response lients a {@link URIRequest#SUCCESS_MESSAGE} if user name and password are valid </br>
	 * and they do not exist in the database when receiving {@link URIRequest#LOGOUT} request from client applications</br>
	 * Otherwise, response a {@link URIRequest#FAILURE_MESSAGE} </br>
	 * 
	 * @param httpExchange {@link HttpExchange} communicates between clients and server </br>
	 * @param parameters contains: </br>
	 * 		</li> {@link UserDAO#USER_NAME}
	 * 		</li> {@link UserDAO#EMAIL}
	 * 		</li> {@link UserDAO#PASSWORD}
	 * 		</li> {@link UserDAO#USER_TYPE_ID}
	 * 
	 */
	public Object doRegister(Map<String, Object> parameters);
	
	/**
	 * 
	 *  @param userKey user key value generated by system when user logins successfully </br>
	 * @return true if {@link UserDAO#USER_KEY} exists, otherwise return false </br>
	 */
	public  boolean hasUserKey(String userKey);
	/**
	 * Add user key value </br>
	 * @param userKey user key value generated by system when user logins successfully </br>
	 */
	public void addUserKey(String userKey);
	/**
	 * Remove user key value out the system </br>
	 * @param userKey user key value generated by system when user logins successfully </br>
	 */
	public void removeUserKey(String userKey);

}
