/**
 * 
 */
package evoter.mobile.utils;

/**
 * @author luongnv89
 */
public class CallBackMessage {
	public static final String EXCITED_BAR_STATISTIC_EVOTER_REQUEST = "EXCITED";
	public static final String DIFFICULT_BAR_STATISTIC_EVOTER_REQUEST = "DIFFICULT";
	public static final String SUBMIT_ANSWER_EVOTER_REQUEST = "SUBMIT_ANSWER_EVOTER_REQUEST";
	public static final String ACCEPT_SESSION_EVOTER_REQUEST = "ACCEPT_SESSION_EVOTER_REQUEST";
	public static final String CHANGE_SESSION_STATUS_EVOTER_REQUEST = "CHANGE_SESSION_STATUS_EVOTER_REQUEST";
	public static final String SUBMIT_STATISTIC_EVOTER_REQUEST = "SUBMIT_STATISTIC_EVOTER_REQUEST";
	public static final String DELETE_QUESTION_EVOTER_REQUEST = "DELETE_QUESTION_EVOTER_REQUEST";
	public static final String STOP_RECEIVE_ANSWER_EVOTER_REQUEST = "STOP_RECEIVE_ANSWER_EVOTER_REQUEST";
	public static final String CHECK_QUESTION_STATUS_EVOTER_REQUEST = "CHECK_QUESTION_STATUS_EVOTER_REQUEST";
	public static final String CHECK_SESSION_STATUS_EVOTER_REQUEST = "CHECK_SESSION_STATUS_EVOTER_REQUEST";
	public static final String SEND_QUESTION_EVOTER_REQUEST = "SEND_QUESTION_EVOTER_REQUEST";
	public static final String GET_LIST_ACCEPTED_STUDENT_EVOTER_REQUEST = "GET_LIST_ACCEPTED_STUDENT_EVOTER_REQUEST";
	public static final String GET_ALL_SUBJECT_EVOTER_REQUEST = "GET_ALL_SUBJECT_EVOTER_REQUEST";
	public static final String GET_ALL_SESSION_EVOTER_REQUEST = "GET_ALL_SESSION_EVOTER_REQUEST";
	public static final String GET_ALL_QUESTION_EVOTER_REQUEST = "GET_ALL_QUESTION_EVOTER_REQUEST";
	public static final String GET_USER_OF_SUBJECT_EVOTER_REQUEST = "GET_USER_OF_SUBJECT_EVOTER_REQUEST";
	public static final String DELETE_SESSION_EVOTER_REQUEST = "DELETE_SESSION_EVOTER_REQUEST";
	public static final String LOGIN_EVOTER_REQUEST = "LOGIN_EVOTER_REQUEST";
	public static final String LOGOUT_EVOTER_REQUEST = "LOGOUT_EVOTER_REQUEST";
	public static final String RESET_PASSWORD_EVOTER_REQUEST = "RESET_PASSWORD_EVOTER_REQUEST";
	public static final String CREATE_USER_EVOTER_REQUEST = "EVOTER_REQUEST_CREATE_USER";
	public static final String UPDATE_QUESTION_EVOTER_REQUEST = "CREATE_USER_EVOTER_REQUEST";
	public static final String UPDATE_SESSION_EVOTER_REQUEST = "EVOTER_REQUEST_UPDATE_SESSION";
	public static final String GET_STATISTIC_EVOTER_REQUEST = "UPDATE_SESSION_EVOTER_REQUEST";
	public static final String CREATE_SESSION_EVOTER_REQUEST = "CREATE_SESSION_EVOTER_REQUEST";
	public static final String CREATE_QUESTION_EVOTER_REQUEST = "CREATE_QUESTION_EVOTER_REQUEST";
	public static final String EDIT_SESSION_EVOTER_REQUEST = "EDIT_SESSION_EVOTER_REQUEST";
	public static final String EDIT_QUESTION_EVOTER_REQUEST = "EDIT_QUESTION_EVOTER_REQUEST";
	
	
}
