/**
 * 
 */
package evoter.mobile.utils;

/**
 * @author luongnv89
 */
public class CallBackMessage {
	public static final String EVOTER_REQUEST_EXCITED_BAR_STATISTIC = "EXCITED";
	public static final String EVOTER_REQUEST_DIFFICULT_BAR_STATISTIC = "DIFFICULT";
	public static final String EVOTER_REQUEST_SUBMIT_ANSWER = "EVOTER_REQUEST_SUBMIT_ANSWER";
	public static final String EVOTER_REQUEST_ACCEPT_SESSION = "EVOTER_REQUEST_ACCEPT_SESSION";
	public static final String EVOTER_REQUEST_CHANGE_SESSION_STATUS = "EVOTER_REQUEST_CHANGE_SESSION_STATUS";
	public static final String EVOTER_REQUEST_SUBMIT_STATISTIC = "EVOTER_REQUEST_SUBMIT_STATISTIC";
	public static final String EVOTER_REQUEST_DELETE_QUESTION = "EVOTER_REQUEST_DELETE_QUESTION";
	public static final String EVOTER_REQUEST_STOP_RECEIVE_ANSWER = "EVOTER_REQUEST_STOP_RECEIVE_ANSWER";
	public static final String EVOTER_REQUEST_CHECK_QUESTION_STATUS = "EVOTER_REQUEST_CHECK_QUESTION_STATUS";
	public static final String EVOTER_REQUEST_CHECK_SESSION_STATUS = "EVOTER_REQUEST_CHECK_SESSION_STATUS";
	public static final String EVOTER_REQUEST_SEND_QUESTION = "EVOTER_REQUEST_SEND_QUESTION";
	public static final String EVOTER_REQUEST_GET_LIST_ACCEPTED_STUDENT = "EVOTER_REQUEST_GET_LIST_ACCEPTED_STUDENT";
}
